name: continuous-deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            whoami
            echo $NODE_ENV
            cd quotemark-server
            git pull origin
            npm install
            npm run build
            npm run migrate:latest