name: continuous-integration
on:
  pull_request:
    branches:
      - dev
env:
  NODE_ENV: test
  PORT: 3000
  DB_CLIENT: mysql
  DB_HOST: localhost
  DB_USER: root
  DB_PASSWORD: very_secret_password
  DB_NAME: quotemark_test
  DB_SEEDERS_DIR: ./seeds/test
  GOOGLE_AUTH_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_CLIENT_ID }}
  GOOGLE_AUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}
  GOOGLE_AUTH_REFRESH_TOKEN: ${{ secrets.GOOGLE_AUTH_REFRESH_TOKEN }}
  GOOGLE_AUTH_USER_EMAIL: ${{ secrets.GOOGLE_AUTH_USER_EMAIL }}
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    services:
      database:
        image: mysql:5.7.36
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: very_secret_password
          MYSQL_DATABASE: quotemark_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.18.0
      - name: Install dependencies
        run: npm install
      - name: Lint the project
        run: npm run eslint
      - name: Build the code
        run: npm run build
      - name: Test
        run: npm run test
