name: continuous-integration
on:
  pull_request:
    branches:
      - dev
env:
  NODE_ENV: test
  PORT: 3000
  DB_CLIENT: mysql
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_SEEDERS_DIR: ${{ secrets.DB_SEEDERS_DIR }}
  GOOGLE_AUTH_CLIENT_ID: ${{ secretsGOOGLE_AUTH_CLIENT_ID. }}
  GOOGLE_AUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}
  GOOGLE_AUTH_REFRESH_TOKEN: ${{ secrets.GOOGLE_AUTH_REFRESH_TOKEN }}
  GOOGLE_AUTH_USER_EMAIL: ${{ secrets.GOOGLE_AUTH_USER_EMAIL }}
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.18.0
      - name: Install dependencies
        run: npm install
      - name: Lint the project
        run: npm run eslint
      - name: Build the code
        run: npm run build
